// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistance_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const assignCoordinatorToAssistanceRequest = `-- name: AssignCoordinatorToAssistanceRequest :one
UPDATE assistance_requests
SET assigned_coordinator_id = $2, status = 'IN_PROGRESS', updated_at = NOW()
WHERE id = $1
RETURNING id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at
`

type AssignCoordinatorToAssistanceRequestParams struct {
	ID                    pgtype.UUID
	AssignedCoordinatorID pgtype.UUID
}

func (q *Queries) AssignCoordinatorToAssistanceRequest(ctx context.Context, arg AssignCoordinatorToAssistanceRequestParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, assignCoordinatorToAssistanceRequest, arg.ID, arg.AssignedCoordinatorID)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedCoordinatorID,
		&i.Location,
		&i.AddressText,
		&i.ContactPhoneEncrypted,
		&i.RequesterNameEncrypted,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssistanceRequest = `-- name: CreateAssistanceRequest :one
INSERT INTO assistance_requests (
    requester_id,
    tracking_code,
    category,
    quantity_needed,
    description,
    priority,
    status,
    location,
    address_text,
    contact_phone_encrypted,
    requester_name_encrypted,
    embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at
`

type CreateAssistanceRequestParams struct {
	RequesterID            pgtype.UUID
	TrackingCode           string
	Category               ResourceCategory
	QuantityNeeded         int32
	Description            pgtype.Text
	Priority               RequestPriority
	Status                 RequestStatus
	Location               string
	AddressText            pgtype.Text
	ContactPhoneEncrypted  string
	RequesterNameEncrypted string
	Embedding              pgvector.Vector
}

func (q *Queries) CreateAssistanceRequest(ctx context.Context, arg CreateAssistanceRequestParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, createAssistanceRequest,
		arg.RequesterID,
		arg.TrackingCode,
		arg.Category,
		arg.QuantityNeeded,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.Location,
		arg.AddressText,
		arg.ContactPhoneEncrypted,
		arg.RequesterNameEncrypted,
		arg.Embedding,
	)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedCoordinatorID,
		&i.Location,
		&i.AddressText,
		&i.ContactPhoneEncrypted,
		&i.RequesterNameEncrypted,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistanceRequestByID = `-- name: GetAssistanceRequestByID :one
SELECT id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at FROM assistance_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssistanceRequestByID(ctx context.Context, id pgtype.UUID) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, getAssistanceRequestByID, id)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedCoordinatorID,
		&i.Location,
		&i.AddressText,
		&i.ContactPhoneEncrypted,
		&i.RequesterNameEncrypted,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistanceRequestByTrackingCode = `-- name: GetAssistanceRequestByTrackingCode :one
SELECT id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at FROM assistance_requests
WHERE tracking_code = $1 LIMIT 1
`

func (q *Queries) GetAssistanceRequestByTrackingCode(ctx context.Context, trackingCode string) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, getAssistanceRequestByTrackingCode, trackingCode)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedCoordinatorID,
		&i.Location,
		&i.AddressText,
		&i.ContactPhoneEncrypted,
		&i.RequesterNameEncrypted,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssistanceRequests = `-- name: ListAssistanceRequests :many
SELECT id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at FROM assistance_requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAssistanceRequestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAssistanceRequests(ctx context.Context, arg ListAssistanceRequestsParams) ([]AssistanceRequest, error) {
	rows, err := q.db.Query(ctx, listAssistanceRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistanceRequest
	for rows.Next() {
		var i AssistanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.TrackingCode,
			&i.Category,
			&i.QuantityNeeded,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedCoordinatorID,
			&i.Location,
			&i.AddressText,
			&i.ContactPhoneEncrypted,
			&i.RequesterNameEncrypted,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistanceRequestsByRequester = `-- name: ListAssistanceRequestsByRequester :many
SELECT id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at FROM assistance_requests
WHERE requester_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAssistanceRequestsByRequesterParams struct {
	RequesterID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListAssistanceRequestsByRequester(ctx context.Context, arg ListAssistanceRequestsByRequesterParams) ([]AssistanceRequest, error) {
	rows, err := q.db.Query(ctx, listAssistanceRequestsByRequester, arg.RequesterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistanceRequest
	for rows.Next() {
		var i AssistanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.TrackingCode,
			&i.Category,
			&i.QuantityNeeded,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedCoordinatorID,
			&i.Location,
			&i.AddressText,
			&i.ContactPhoneEncrypted,
			&i.RequesterNameEncrypted,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssistanceRequestStatus = `-- name: UpdateAssistanceRequestStatus :one
UPDATE assistance_requests
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, requester_id, tracking_code, category, quantity_needed, description, priority, status, assigned_coordinator_id, location, address_text, contact_phone_encrypted, requester_name_encrypted, embedding, created_at, updated_at
`

type UpdateAssistanceRequestStatusParams struct {
	ID     pgtype.UUID
	Status RequestStatus
}

func (q *Queries) UpdateAssistanceRequestStatus(ctx context.Context, arg UpdateAssistanceRequestStatusParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAssistanceRequestStatus, arg.ID, arg.Status)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedCoordinatorID,
		&i.Location,
		&i.AddressText,
		&i.ContactPhoneEncrypted,
		&i.RequesterNameEncrypted,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
