// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disaster_reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisasterReport = `-- name: CreateDisasterReport :one
INSERT INTO disaster_report (
    reporter_id,
    embedding,
    location
) VALUES (
    $1, $2, $3
)
RETURNING id, reporter_id, embedding, location, created_at
`

type CreateDisasterReportParams struct {
	ReporterID pgtype.UUID
	Embedding  string
	Location   string
}

func (q *Queries) CreateDisasterReport(ctx context.Context, arg CreateDisasterReportParams) (DisasterReport, error) {
	row := q.db.QueryRow(ctx, createDisasterReport, arg.ReporterID, arg.Embedding, arg.Location)
	var i DisasterReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Embedding,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getDisasterReportByID = `-- name: GetDisasterReportByID :one
SELECT id, reporter_id, embedding, location, created_at FROM disaster_report
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDisasterReportByID(ctx context.Context, id pgtype.UUID) (DisasterReport, error) {
	row := q.db.QueryRow(ctx, getDisasterReportByID, id)
	var i DisasterReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Embedding,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listDisasterReports = `-- name: ListDisasterReports :many
SELECT id, reporter_id, embedding, location, created_at FROM disaster_report
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDisasterReportsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDisasterReports(ctx context.Context, arg ListDisasterReportsParams) ([]DisasterReport, error) {
	rows, err := q.db.Query(ctx, listDisasterReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisasterReport
	for rows.Next() {
		var i DisasterReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.Embedding,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisasterReportsByReporter = `-- name: ListDisasterReportsByReporter :many
SELECT id, reporter_id, embedding, location, created_at FROM disaster_report
WHERE reporter_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDisasterReportsByReporterParams struct {
	ReporterID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListDisasterReportsByReporter(ctx context.Context, arg ListDisasterReportsByReporterParams) ([]DisasterReport, error) {
	rows, err := q.db.Query(ctx, listDisasterReportsByReporter, arg.ReporterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisasterReport
	for rows.Next() {
		var i DisasterReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.Embedding,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
