// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispatch.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDispatchMatch = `-- name: CreateDispatchMatch :one
INSERT INTO dispatch_matches (
    request_id, provider_id, handshake_code, status
) VALUES ($1, $2, $3, 'ACTIVE')
RETURNING id, request_id, provider_id, cluster_id, handshake_code, status, completed_at, created_at
`

type CreateDispatchMatchParams struct {
	RequestID     pgtype.UUID
	ProviderID    pgtype.UUID
	HandshakeCode string
}

func (q *Queries) CreateDispatchMatch(ctx context.Context, arg CreateDispatchMatchParams) (DispatchMatch, error) {
	row := q.db.QueryRow(ctx, createDispatchMatch, arg.RequestID, arg.ProviderID, arg.HandshakeCode)
	var i DispatchMatch
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProviderID,
		&i.ClusterID,
		&i.HandshakeCode,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDispatchPing = `-- name: CreateDispatchPing :one
INSERT INTO dispatch_pings (
    request_id, provider_id, ping_order, status, expires_at
) VALUES ($1, $2, $3, 'PENDING', $4)
RETURNING id, request_id, provider_id, ping_order, status, expires_at, responded_at, created_at
`

type CreateDispatchPingParams struct {
	RequestID  pgtype.UUID
	ProviderID pgtype.UUID
	PingOrder  int32
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateDispatchPing(ctx context.Context, arg CreateDispatchPingParams) (DispatchPing, error) {
	row := q.db.QueryRow(ctx, createDispatchPing,
		arg.RequestID,
		arg.ProviderID,
		arg.PingOrder,
		arg.ExpiresAt,
	)
	var i DispatchPing
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProviderID,
		&i.PingOrder,
		&i.Status,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deductProviderResourceCapacityByCategory = `-- name: DeductProviderResourceCapacityByCategory :exec
UPDATE resources
SET current_capacity = GREATEST(0, resources.current_capacity - $3),
    last_updated_at = NOW()
WHERE id = (
    SELECT r2.id FROM resources r2
    WHERE r2.provider_id = $1 AND r2.category = $2 AND r2.current_capacity >= $3 AND r2.status != 'UNAVAILABLE'
    ORDER BY r2.current_capacity DESC
    LIMIT 1
)
`

type DeductProviderResourceCapacityByCategoryParams struct {
	ProviderID      pgtype.UUID
	Category        ResourceCategory
	CurrentCapacity int32
}

func (q *Queries) DeductProviderResourceCapacityByCategory(ctx context.Context, arg DeductProviderResourceCapacityByCategoryParams) error {
	_, err := q.db.Exec(ctx, deductProviderResourceCapacityByCategory, arg.ProviderID, arg.Category, arg.CurrentCapacity)
	return err
}

const deductResourceCapacity = `-- name: DeductResourceCapacity :exec
UPDATE resources
SET current_capacity = GREATEST(0, current_capacity - $2),
    last_updated_at = NOW()
WHERE id = $1
`

type DeductResourceCapacityParams struct {
	ID              pgtype.UUID
	CurrentCapacity int32
}

func (q *Queries) DeductResourceCapacity(ctx context.Context, arg DeductResourceCapacityParams) error {
	_, err := q.db.Exec(ctx, deductResourceCapacity, arg.ID, arg.CurrentCapacity)
	return err
}

const findCandidateProvidersForRequest = `-- name: FindCandidateProvidersForRequest :many
SELECT 
    p.id AS provider_id,
    p.name AS provider_name,
    p.ph_no AS provider_phone,
    r.id AS resource_id,
    r.title AS resource_title,
    r.current_capacity AS resource_capacity,
    ROUND(ST_Distance(p.location::geography, ar.location::geography))::bigint AS distance_meters
FROM assistance_requests ar
CROSS JOIN providers p
JOIN LATERAL (
    SELECT id, title, current_capacity 
    FROM resources 
    WHERE provider_id = p.id 
      AND (category = ar.category OR ar.category = 'OTHER' OR category = 'OTHER')
      AND current_capacity >= ar.quantity_needed
      AND status != 'UNAVAILABLE'
    ORDER BY current_capacity DESC
    LIMIT 1
) r ON true
WHERE ar.id = $1
  AND p.is_available = TRUE
  AND p.current_active_tasks < p.max_active_tasks
  AND NOT EXISTS (
      SELECT 1 FROM dispatch_pings dp 
      WHERE dp.request_id = ar.id AND dp.provider_id = p.id
  )
ORDER BY ST_Distance(p.location::geography, ar.location::geography) ASC
LIMIT $2
`

type FindCandidateProvidersForRequestParams struct {
	ID    pgtype.UUID
	Limit int32
}

type FindCandidateProvidersForRequestRow struct {
	ProviderID       pgtype.UUID
	ProviderName     string
	ProviderPhone    string
	ResourceID       pgtype.UUID
	ResourceTitle    string
	ResourceCapacity int32
	DistanceMeters   int64
}

func (q *Queries) FindCandidateProvidersForRequest(ctx context.Context, arg FindCandidateProvidersForRequestParams) ([]FindCandidateProvidersForRequestRow, error) {
	rows, err := q.db.Query(ctx, findCandidateProvidersForRequest, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCandidateProvidersForRequestRow
	for rows.Next() {
		var i FindCandidateProvidersForRequestRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderName,
			&i.ProviderPhone,
			&i.ResourceID,
			&i.ResourceTitle,
			&i.ResourceCapacity,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePingForProvider = `-- name: GetActivePingForProvider :one
SELECT 
    dp.id AS ping_id,
    dp.request_id,
    dp.provider_id,
    dp.ping_order,
    dp.status,
    dp.expires_at,
    dp.created_at,
    ar.tracking_code,
    ar.category,
    ar.quantity_needed,
    ar.description,
    ar.address_text,
    ROUND(ST_Distance(p.location::geography, ar.location::geography))::bigint AS distance_meters
FROM dispatch_pings dp
JOIN assistance_requests ar ON ar.id = dp.request_id
JOIN providers p ON p.id = dp.provider_id
WHERE dp.provider_id = $1 AND dp.status = 'PENDING' AND dp.expires_at > NOW()
ORDER BY dp.created_at DESC
LIMIT 1
`

type GetActivePingForProviderRow struct {
	PingID         pgtype.UUID
	RequestID      pgtype.UUID
	ProviderID     pgtype.UUID
	PingOrder      int32
	Status         DispatchPingStatus
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	TrackingCode   string
	Category       ResourceCategory
	QuantityNeeded int32
	Description    pgtype.Text
	AddressText    pgtype.Text
	DistanceMeters int64
}

func (q *Queries) GetActivePingForProvider(ctx context.Context, providerID pgtype.UUID) (GetActivePingForProviderRow, error) {
	row := q.db.QueryRow(ctx, getActivePingForProvider, providerID)
	var i GetActivePingForProviderRow
	err := row.Scan(
		&i.PingID,
		&i.RequestID,
		&i.ProviderID,
		&i.PingOrder,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TrackingCode,
		&i.Category,
		&i.QuantityNeeded,
		&i.Description,
		&i.AddressText,
		&i.DistanceMeters,
	)
	return i, err
}

const getExhaustedRequests = `-- name: GetExhaustedRequests :many
SELECT 
    id, tracking_code, category, quantity_needed, description, priority, 
    status, dispatch_status, address_text, created_at, updated_at
FROM assistance_requests
WHERE dispatch_status = 'EXHAUSTED'
ORDER BY priority_score DESC, created_at DESC
`

type GetExhaustedRequestsRow struct {
	ID             pgtype.UUID
	TrackingCode   string
	Category       ResourceCategory
	QuantityNeeded int32
	Description    pgtype.Text
	Priority       RequestPriority
	Status         RequestStatus
	DispatchStatus DispatchStatus
	AddressText    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetExhaustedRequests(ctx context.Context) ([]GetExhaustedRequestsRow, error) {
	rows, err := q.db.Query(ctx, getExhaustedRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExhaustedRequestsRow
	for rows.Next() {
		var i GetExhaustedRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrackingCode,
			&i.Category,
			&i.QuantityNeeded,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DispatchStatus,
			&i.AddressText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPings = `-- name: GetExpiredPings :many
SELECT id, request_id, provider_id, ping_order, status, expires_at, responded_at, created_at FROM dispatch_pings
WHERE status = 'PENDING' AND expires_at <= NOW()
ORDER BY expires_at ASC
`

func (q *Queries) GetExpiredPings(ctx context.Context) ([]DispatchPing, error) {
	rows, err := q.db.Query(ctx, getExpiredPings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchPing
	for rows.Next() {
		var i DispatchPing
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProviderID,
			&i.PingOrder,
			&i.Status,
			&i.ExpiresAt,
			&i.RespondedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByRequestID = `-- name: GetMatchByRequestID :one
SELECT 
    dm.id,
    dm.request_id,
    dm.provider_id,
    dm.cluster_id,
    dm.handshake_code,
    dm.status,
    dm.completed_at,
    dm.created_at,
    p.name AS provider_name,
    p.ph_no AS provider_phone
FROM dispatch_matches dm
JOIN providers p ON p.id = dm.provider_id
WHERE dm.request_id = $1
`

type GetMatchByRequestIDRow struct {
	ID            pgtype.UUID
	RequestID     pgtype.UUID
	ProviderID    pgtype.UUID
	ClusterID     pgtype.UUID
	HandshakeCode string
	Status        MatchStatus
	CompletedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	ProviderName  string
	ProviderPhone string
}

func (q *Queries) GetMatchByRequestID(ctx context.Context, requestID pgtype.UUID) (GetMatchByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByRequestID, requestID)
	var i GetMatchByRequestIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProviderID,
		&i.ClusterID,
		&i.HandshakeCode,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ProviderName,
		&i.ProviderPhone,
	)
	return i, err
}

const getNextPingOrderForRequest = `-- name: GetNextPingOrderForRequest :one
SELECT COALESCE(MAX(ping_order), 0) + 1 AS next_order
FROM dispatch_pings
WHERE request_id = $1
`

func (q *Queries) GetNextPingOrderForRequest(ctx context.Context, requestID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPingOrderForRequest, requestID)
	var next_order int32
	err := row.Scan(&next_order)
	return next_order, err
}

const getPingByID = `-- name: GetPingByID :one
SELECT id, request_id, provider_id, ping_order, status, expires_at, responded_at, created_at FROM dispatch_pings
WHERE id = $1
`

func (q *Queries) GetPingByID(ctx context.Context, id pgtype.UUID) (DispatchPing, error) {
	row := q.db.QueryRow(ctx, getPingByID, id)
	var i DispatchPing
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProviderID,
		&i.PingOrder,
		&i.Status,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasActivePingForRequest = `-- name: HasActivePingForRequest :one
SELECT EXISTS (
    SELECT 1 FROM dispatch_pings
    WHERE request_id = $1 AND status = 'PENDING' AND expires_at > NOW()
)
`

func (q *Queries) HasActivePingForRequest(ctx context.Context, requestID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActivePingForRequest, requestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementProviderActiveTasks = `-- name: IncrementProviderActiveTasks :exec
UPDATE providers
SET current_active_tasks = current_active_tasks + 1,
    last_updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementProviderActiveTasks(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementProviderActiveTasks, id)
	return err
}

const markRequestDispatching = `-- name: MarkRequestDispatching :exec
UPDATE assistance_requests
SET dispatch_status = 'DISPATCHING',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRequestDispatching(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRequestDispatching, id)
	return err
}

const markRequestExhausted = `-- name: MarkRequestExhausted :exec
UPDATE assistance_requests
SET dispatch_status = 'EXHAUSTED',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRequestExhausted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRequestExhausted, id)
	return err
}

const markRequestMatched = `-- name: MarkRequestMatched :exec
UPDATE assistance_requests
SET dispatch_status = 'MATCHED',
    status = 'IN_PROGRESS',
    matched_provider_id = $2,
    matched_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkRequestMatchedParams struct {
	ID                pgtype.UUID
	MatchedProviderID pgtype.UUID
}

func (q *Queries) MarkRequestMatched(ctx context.Context, arg MarkRequestMatchedParams) error {
	_, err := q.db.Exec(ctx, markRequestMatched, arg.ID, arg.MatchedProviderID)
	return err
}

const updatePingStatus = `-- name: UpdatePingStatus :one
UPDATE dispatch_pings
SET status = $2, responded_at = NOW()
WHERE id = $1
RETURNING id, request_id, provider_id, ping_order, status, expires_at, responded_at, created_at
`

type UpdatePingStatusParams struct {
	ID     pgtype.UUID
	Status DispatchPingStatus
}

func (q *Queries) UpdatePingStatus(ctx context.Context, arg UpdatePingStatusParams) (DispatchPing, error) {
	row := q.db.QueryRow(ctx, updatePingStatus, arg.ID, arg.Status)
	var i DispatchPing
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProviderID,
		&i.PingOrder,
		&i.Status,
		&i.ExpiresAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}
