// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProviderType string

const (
	ProviderTypeORGANISATION ProviderType = "ORGANISATION"
	ProviderTypeINDIVIDUAL   ProviderType = "INDIVIDUAL"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType
	Valid        bool // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type UserRole string

const (
	UserRoleGUEST       UserRole = "GUEST"
	UserRoleVICTIM      UserRole = "VICTIM"
	UserRolePUBLIC      UserRole = "PUBLIC"
	UserRolePROVIDER    UserRole = "PROVIDER"
	UserRoleCOORDINATOR UserRole = "COORDINATOR"
	UserRoleADMIN       UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Provider struct {
	ID               pgtype.UUID
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	PasswordHash     string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
	LastUpdatedAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Phone        string
	PasswordHash string
	Role         UserRole
	FullName     string
	CreatedAt    pgtype.Timestamptz
}
