// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mutual_aid_items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimMutualAidItem = `-- name: ClaimMutualAidItem :one
UPDATE mutual_aid_items
SET is_claimed = TRUE, claimed_by_user_id = $2
WHERE id = $1 AND is_claimed = FALSE
RETURNING id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at
`

type ClaimMutualAidItemParams struct {
	ID              pgtype.UUID
	ClaimedByUserID pgtype.UUID
}

func (q *Queries) ClaimMutualAidItem(ctx context.Context, arg ClaimMutualAidItemParams) (MutualAidItem, error) {
	row := q.db.QueryRow(ctx, claimMutualAidItem, arg.ID, arg.ClaimedByUserID)
	var i MutualAidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemName,
		&i.Quantity,
		&i.Description,
		&i.Location,
		&i.IsClaimed,
		&i.ClaimedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createMutualAidItem = `-- name: CreateMutualAidItem :one
INSERT INTO mutual_aid_items (
    user_id,
    item_name,
    quantity,
    description,
    location,
    is_claimed
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at
`

type CreateMutualAidItemParams struct {
	UserID      pgtype.UUID
	ItemName    string
	Quantity    int32
	Description pgtype.Text
	Location    string
	IsClaimed   bool
}

func (q *Queries) CreateMutualAidItem(ctx context.Context, arg CreateMutualAidItemParams) (MutualAidItem, error) {
	row := q.db.QueryRow(ctx, createMutualAidItem,
		arg.UserID,
		arg.ItemName,
		arg.Quantity,
		arg.Description,
		arg.Location,
		arg.IsClaimed,
	)
	var i MutualAidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemName,
		&i.Quantity,
		&i.Description,
		&i.Location,
		&i.IsClaimed,
		&i.ClaimedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMutualAidItemByID = `-- name: GetMutualAidItemByID :one
SELECT id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at FROM mutual_aid_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMutualAidItemByID(ctx context.Context, id pgtype.UUID) (MutualAidItem, error) {
	row := q.db.QueryRow(ctx, getMutualAidItemByID, id)
	var i MutualAidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemName,
		&i.Quantity,
		&i.Description,
		&i.Location,
		&i.IsClaimed,
		&i.ClaimedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailableMutualAidItems = `-- name: ListAvailableMutualAidItems :many
SELECT id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at FROM mutual_aid_items
WHERE is_claimed = FALSE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAvailableMutualAidItemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAvailableMutualAidItems(ctx context.Context, arg ListAvailableMutualAidItemsParams) ([]MutualAidItem, error) {
	rows, err := q.db.Query(ctx, listAvailableMutualAidItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutualAidItem
	for rows.Next() {
		var i MutualAidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemName,
			&i.Quantity,
			&i.Description,
			&i.Location,
			&i.IsClaimed,
			&i.ClaimedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualAidItems = `-- name: ListMutualAidItems :many
SELECT id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at FROM mutual_aid_items
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMutualAidItemsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMutualAidItems(ctx context.Context, arg ListMutualAidItemsParams) ([]MutualAidItem, error) {
	rows, err := q.db.Query(ctx, listMutualAidItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutualAidItem
	for rows.Next() {
		var i MutualAidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemName,
			&i.Quantity,
			&i.Description,
			&i.Location,
			&i.IsClaimed,
			&i.ClaimedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualAidItemsByUser = `-- name: ListMutualAidItemsByUser :many
SELECT id, user_id, item_name, quantity, description, location, is_claimed, claimed_by_user_id, created_at FROM mutual_aid_items
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMutualAidItemsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListMutualAidItemsByUser(ctx context.Context, arg ListMutualAidItemsByUserParams) ([]MutualAidItem, error) {
	rows, err := q.db.Query(ctx, listMutualAidItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MutualAidItem
	for rows.Next() {
		var i MutualAidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemName,
			&i.Quantity,
			&i.Description,
			&i.Location,
			&i.IsClaimed,
			&i.ClaimedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
