// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
    type,
    authorized_person,
    name,
    password_hash,
    registration_no,
    govt_id,
    cin,
    email,
    ph_no,
    website,
    state,
    dist,
    location
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, type, authorized_person, name, registration_no, govt_id, cin, email, ph_no, website, state, dist, location, last_updated_at, created_at
`

type CreateProviderParams struct {
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	PasswordHash     string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
}

type CreateProviderRow struct {
	ID               pgtype.UUID
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
	LastUpdatedAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (CreateProviderRow, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Type,
		arg.AuthorizedPerson,
		arg.Name,
		arg.PasswordHash,
		arg.RegistrationNo,
		arg.GovtID,
		arg.Cin,
		arg.Email,
		arg.PhNo,
		arg.Website,
		arg.State,
		arg.Dist,
		arg.Location,
	)
	var i CreateProviderRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AuthorizedPerson,
		&i.Name,
		&i.RegistrationNo,
		&i.GovtID,
		&i.Cin,
		&i.Email,
		&i.PhNo,
		&i.Website,
		&i.State,
		&i.Dist,
		&i.Location,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderByEmail = `-- name: GetProviderByEmail :one
SELECT id, type, authorized_person, name, password_hash, registration_no, govt_id, cin, email, ph_no, website, state, dist, location, last_updated_at, created_at
FROM providers
WHERE email = $1
`

type GetProviderByEmailRow struct {
	ID               pgtype.UUID
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	PasswordHash     string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
	LastUpdatedAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetProviderByEmail(ctx context.Context, email string) (GetProviderByEmailRow, error) {
	row := q.db.QueryRow(ctx, getProviderByEmail, email)
	var i GetProviderByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AuthorizedPerson,
		&i.Name,
		&i.PasswordHash,
		&i.RegistrationNo,
		&i.GovtID,
		&i.Cin,
		&i.Email,
		&i.PhNo,
		&i.Website,
		&i.State,
		&i.Dist,
		&i.Location,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, type, authorized_person, name, registration_no, govt_id, cin, email, ph_no, website, state, dist, location, last_updated_at, created_at
FROM providers
WHERE id = $1
`

type GetProviderByIDRow struct {
	ID               pgtype.UUID
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
	LastUpdatedAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (GetProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i GetProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AuthorizedPerson,
		&i.Name,
		&i.RegistrationNo,
		&i.GovtID,
		&i.Cin,
		&i.Email,
		&i.PhNo,
		&i.Website,
		&i.State,
		&i.Dist,
		&i.Location,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderByPhone = `-- name: GetProviderByPhone :one
SELECT id, type, authorized_person, name, password_hash, registration_no, govt_id, cin, email, ph_no, website, state, dist, location, last_updated_at, created_at
FROM providers
WHERE ph_no = $1
`

type GetProviderByPhoneRow struct {
	ID               pgtype.UUID
	Type             ProviderType
	AuthorizedPerson pgtype.Text
	Name             string
	PasswordHash     string
	RegistrationNo   pgtype.Text
	GovtID           string
	Cin              pgtype.Text
	Email            string
	PhNo             string
	Website          pgtype.Text
	State            string
	Dist             string
	Location         string
	LastUpdatedAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetProviderByPhone(ctx context.Context, phNo string) (GetProviderByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getProviderByPhone, phNo)
	var i GetProviderByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AuthorizedPerson,
		&i.Name,
		&i.PasswordHash,
		&i.RegistrationNo,
		&i.GovtID,
		&i.Cin,
		&i.Email,
		&i.PhNo,
		&i.Website,
		&i.State,
		&i.Dist,
		&i.Location,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
