// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
    provider_id,
    title,
    description,
    category,
    total_capacity,
    current_capacity,
    unit,
    status,
    location,
    contact_phone,
    image_url,
    embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at
`

type CreateResourceParams struct {
	ProviderID      pgtype.UUID
	Title           string
	Description     pgtype.Text
	Category        ResourceCategory
	TotalCapacity   int32
	CurrentCapacity int32
	Unit            pgtype.Text
	Status          VerificationStatus
	Location        string
	ContactPhone    pgtype.Text
	ImageUrl        pgtype.Text
	Embedding       pgvector.Vector
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ProviderID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TotalCapacity,
		arg.CurrentCapacity,
		arg.Unit,
		arg.Status,
		arg.Location,
		arg.ContactPhone,
		arg.ImageUrl,
		arg.Embedding,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TotalCapacity,
		&i.CurrentCapacity,
		&i.Unit,
		&i.Status,
		&i.Location,
		&i.ContactPhone,
		&i.ImageUrl,
		&i.Embedding,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = $1 AND provider_id = $2
`

type DeleteResourceParams struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.Exec(ctx, deleteResource, arg.ID, arg.ProviderID)
	return err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at FROM resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResourceByID(ctx context.Context, id pgtype.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TotalCapacity,
		&i.CurrentCapacity,
		&i.Unit,
		&i.Status,
		&i.Location,
		&i.ContactPhone,
		&i.ImageUrl,
		&i.Embedding,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at FROM resources
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListResourcesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TotalCapacity,
			&i.CurrentCapacity,
			&i.Unit,
			&i.Status,
			&i.Location,
			&i.ContactPhone,
			&i.ImageUrl,
			&i.Embedding,
			&i.LastUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCategory = `-- name: ListResourcesByCategory :many
SELECT id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at FROM resources
WHERE category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByCategoryParams struct {
	Category ResourceCategory
	Limit    int32
	Offset   int32
}

func (q *Queries) ListResourcesByCategory(ctx context.Context, arg ListResourcesByCategoryParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TotalCapacity,
			&i.CurrentCapacity,
			&i.Unit,
			&i.Status,
			&i.Location,
			&i.ContactPhone,
			&i.ImageUrl,
			&i.Embedding,
			&i.LastUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByProvider = `-- name: ListResourcesByProvider :many
SELECT id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at FROM resources
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResourcesByProviderParams struct {
	ProviderID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListResourcesByProvider(ctx context.Context, arg ListResourcesByProviderParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.TotalCapacity,
			&i.CurrentCapacity,
			&i.Unit,
			&i.Status,
			&i.Location,
			&i.ContactPhone,
			&i.ImageUrl,
			&i.Embedding,
			&i.LastUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title = $2,
    description = $3,
    category = $4,
    total_capacity = $5,
    current_capacity = $6,
    unit = $7,
    contact_phone = $8,
    image_url = $9,
    last_updated_at = NOW()
WHERE id = $1 AND provider_id = $10
RETURNING id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at
`

type UpdateResourceParams struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	Category        ResourceCategory
	TotalCapacity   int32
	CurrentCapacity int32
	Unit            pgtype.Text
	ContactPhone    pgtype.Text
	ImageUrl        pgtype.Text
	ProviderID      pgtype.UUID
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.TotalCapacity,
		arg.CurrentCapacity,
		arg.Unit,
		arg.ContactPhone,
		arg.ImageUrl,
		arg.ProviderID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TotalCapacity,
		&i.CurrentCapacity,
		&i.Unit,
		&i.Status,
		&i.Location,
		&i.ContactPhone,
		&i.ImageUrl,
		&i.Embedding,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateResourceCapacity = `-- name: UpdateResourceCapacity :one
UPDATE resources
SET current_capacity = $2, last_updated_at = NOW()
WHERE id = $1
RETURNING id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at
`

type UpdateResourceCapacityParams struct {
	ID              pgtype.UUID
	CurrentCapacity int32
}

func (q *Queries) UpdateResourceCapacity(ctx context.Context, arg UpdateResourceCapacityParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceCapacity, arg.ID, arg.CurrentCapacity)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TotalCapacity,
		&i.CurrentCapacity,
		&i.Unit,
		&i.Status,
		&i.Location,
		&i.ContactPhone,
		&i.ImageUrl,
		&i.Embedding,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources
SET status = $2, last_updated_at = NOW()
WHERE id = $1
RETURNING id, provider_id, title, description, category, total_capacity, current_capacity, unit, status, location, contact_phone, image_url, embedding, last_updated_at, created_at
`

type UpdateResourceStatusParams struct {
	ID     pgtype.UUID
	Status VerificationStatus
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus, arg.ID, arg.Status)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.TotalCapacity,
		&i.CurrentCapacity,
		&i.Unit,
		&i.Status,
		&i.Location,
		&i.ContactPhone,
		&i.ImageUrl,
		&i.Embedding,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
