// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: road_hazards.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoadHazard = `-- name: CreateRoadHazard :one
INSERT INTO road_hazards (
    reporter_id,
    reporter_name,
    reporter_phone,
    hazard_type,
    severity,
    location,
    description,
    is_verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, reporter_id, reporter_name, reporter_phone, hazard_type, severity, location, description, is_verified, created_at
`

type CreateRoadHazardParams struct {
	ReporterID    pgtype.UUID
	ReporterName  pgtype.Text
	ReporterPhone pgtype.Text
	HazardType    string
	Severity      string
	Location      string
	Description   pgtype.Text
	IsVerified    bool
}

func (q *Queries) CreateRoadHazard(ctx context.Context, arg CreateRoadHazardParams) (RoadHazard, error) {
	row := q.db.QueryRow(ctx, createRoadHazard,
		arg.ReporterID,
		arg.ReporterName,
		arg.ReporterPhone,
		arg.HazardType,
		arg.Severity,
		arg.Location,
		arg.Description,
		arg.IsVerified,
	)
	var i RoadHazard
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReporterName,
		&i.ReporterPhone,
		&i.HazardType,
		&i.Severity,
		&i.Location,
		&i.Description,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadHazardByID = `-- name: GetRoadHazardByID :one
SELECT id, reporter_id, reporter_name, reporter_phone, hazard_type, severity, location, description, is_verified, created_at FROM road_hazards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoadHazardByID(ctx context.Context, id pgtype.UUID) (RoadHazard, error) {
	row := q.db.QueryRow(ctx, getRoadHazardByID, id)
	var i RoadHazard
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReporterName,
		&i.ReporterPhone,
		&i.HazardType,
		&i.Severity,
		&i.Location,
		&i.Description,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const listRoadHazards = `-- name: ListRoadHazards :many
SELECT id, reporter_id, reporter_name, reporter_phone, hazard_type, severity, location, description, is_verified, created_at FROM road_hazards
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoadHazardsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRoadHazards(ctx context.Context, arg ListRoadHazardsParams) ([]RoadHazard, error) {
	rows, err := q.db.Query(ctx, listRoadHazards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadHazard
	for rows.Next() {
		var i RoadHazard
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterName,
			&i.ReporterPhone,
			&i.HazardType,
			&i.Severity,
			&i.Location,
			&i.Description,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoadHazardsByReporter = `-- name: ListRoadHazardsByReporter :many
SELECT id, reporter_id, reporter_name, reporter_phone, hazard_type, severity, location, description, is_verified, created_at FROM road_hazards
WHERE reporter_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRoadHazardsByReporterParams struct {
	ReporterID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListRoadHazardsByReporter(ctx context.Context, arg ListRoadHazardsByReporterParams) ([]RoadHazard, error) {
	rows, err := q.db.Query(ctx, listRoadHazardsByReporter, arg.ReporterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadHazard
	for rows.Next() {
		var i RoadHazard
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterName,
			&i.ReporterPhone,
			&i.HazardType,
			&i.Severity,
			&i.Location,
			&i.Description,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyRoadHazard = `-- name: VerifyRoadHazard :one
UPDATE road_hazards
SET is_verified = $2
WHERE id = $1
RETURNING id, reporter_id, reporter_name, reporter_phone, hazard_type, severity, location, description, is_verified, created_at
`

type VerifyRoadHazardParams struct {
	ID         pgtype.UUID
	IsVerified bool
}

func (q *Queries) VerifyRoadHazard(ctx context.Context, arg VerifyRoadHazardParams) (RoadHazard, error) {
	row := q.db.QueryRow(ctx, verifyRoadHazard, arg.ID, arg.IsVerified)
	var i RoadHazard
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReporterName,
		&i.ReporterPhone,
		&i.HazardType,
		&i.Severity,
		&i.Location,
		&i.Description,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}
