// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    phone,
    password_hash,
    role,
    full_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, phone, role, full_name, created_at
`

type CreateUserParams struct {
	Phone        string
	PasswordHash string
	Role         UserRole
	FullName     string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Phone     string
	Role      UserRole
	FullName  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, role, full_name, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Phone     string
	Role      UserRole
	FullName  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, role, full_name, created_at
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}
