// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    phone,
    password_hash,
    role,
    full_name,
    location
) VALUES (
    $1, 
    $2, 
    $3, 
    $4,
    CASE 
        WHEN $5::text != '' AND $5::text IS NOT NULL THEN ST_GeomFromText($5::text, 4326)
        ELSE NULL
    END
)
RETURNING id, phone, role, full_name, COALESCE(ST_AsText(location), '')::text as location, created_at
`

type CreateUserParams struct {
	Phone        string
	PasswordHash string
	Role         UserRole
	FullName     string
	Location     string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Phone     string
	Role      UserRole
	FullName  string
	Location  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
		arg.Location,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.FullName,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, role, full_name, COALESCE(ST_AsText(location), '')::text as location, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Phone     string
	Role      UserRole
	FullName  string
	Location  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.FullName,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, role, full_name, COALESCE(ST_AsText(location), '')::text as location, created_at
FROM users
WHERE phone = $1
`

type GetUserByPhoneRow struct {
	ID           pgtype.UUID
	Phone        string
	PasswordHash string
	Role         UserRole
	FullName     string
	Location     string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}
